### ISSUE TITLE
HttpRequest::getUrlPath() should return a string

### ISSUE THREAD

**Issue by nullproxy** [kusanagi/katana-sdk-php7#36]
When a path does not exist in the URL, the `HttpRequest::getUrlPath()` method should return an empty *string*, but it currently returns `NULL`.

This was using version **1.1.4** of the framework, with system info below:

```
Linux work 4.2.0-42-generic #49~14.04.1-Ubuntu SMP Wed Jun 29 20:22:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by fcastilloes** [comment]
Will hit 1.1.5

**Comment by nullproxy** [comment]
:+1:
