### ISSUE TITLE
Request::newResponse() arguments should be optional

### ISSUE THREAD

**Issue by nullproxy** [kusanagi/katana-sdk-php7#37]
The `Request::newResponse()` method currently expects arguments, but the 2 arguments should be optional, falling back to `200` and `"OK"` respectively.

The following error is returned:

```
Callback error: Language error (shutdown) (1) Uncaught TypeError: Argument 1 passed to Katana\\Sdk\\Api\\RequestApi::newResponse() must be of the type integer, none given, called in /middleware.php on line 27 and defined in /vendor/kusanagi/katana-sdk-php7/src/Api/RequestApi.php
```

This was using version **1.1.4** of the framework, with system info below:

```
Linux work 4.2.0-42-generic #49~14.04.1-Ubuntu SMP Wed Jun 29 20:22:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by fcastilloes** [comment]
Are you sure you actually tried with version *1.1.4*? That was fixed for *1.1.1*.

https://github.com/kusanagi/katana-sdk-php7/commit/3fdfa8d0c7a8bda967693c84ff1ffd2e0be51fc5

**Comment by nullproxy** [comment]
The required dependency is "kusanagi/katana-sdk-php7", with the version constraint set as "^1.1".

When running `composer show` it gives the following:

```
kusanagi/katana-sdk-php7 1.1.x-dev f098bc2
```

Which corresponds the the latest commit on the [1.1](https://github.com/kusanagi/katana-sdk-php7/commits/1.1) branch.

**Comment by fcastilloes** [comment]
Ok, version branches were not being updated. Merged now.

**Comment by nullproxy** [comment]
OK, confirmed that this is resolved.
