### ISSUE TITLE
Capture error when file comes to a service without a token

### ISSUE THREAD

**Issue by HugoRuiz** [kusanagi/katana-sdk-php7#85]
Error appear when a file comes to the service with an http path but without a token.

```
[31-Oct-2017 12:44:49 UTC] PHP Fatal error:  Uncaught Katana\Sdk\Exception\InvalidValueException: Missing token for File: body in .../vendor/kusanagi/katana-sdk-php7/src/Api/File.php:96
```

**Comment by fcastilloes** [comment]
That happens when a token for a file in the command message is missing, which should not happens.

Anyways, I've prepared a patch that will capture most of what could happen during the parsing. That way the request will fail anyways, but the component won't crash. Will land in `1.2.7`.
